# Generated by Django 4.2.5 on 2023-09-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="user_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
