# Generated by Django 4.2.5 on 2023-09-30 04:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("data_events", "0003_alter_purchase_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="session_id",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchase",
            name="session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
